name: "Trivy GitHub Issues"
description: "Create GitHub Issues according to the Trivy result"
inputs:
  label:
    description: "The label name"
    required: false
    default: "vulnerability"
  severity:
    description: "Severities of vulnerabilities"
    required: false
    default: "CRITICAL"
  skip-dirs:
    description: "comma separated list of directories where traversal is skipped"
    required: false
    default: ""
  assignee:
    description: "Assignee"
    required: false
  project-id:
    description: "GitHub Project ID"
    required: false
runs:
  using: "composite"
  steps:
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@0.2.2
      with:
        scan-type: "fs"
        ignore-unfixed: true
        format: "json"
        output: "result.json"
        severity: ${{ inputs.severity }}
        skip-dirs: ${{ inputs.skip-dirs }}
    - name: Create GitHub Issues
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_LABEL: ${{ inputs.label }}
        INPUT_ASSIGNEE: ${{ inputs.assignee }}
        INPUT_PROJECT_ID: ${{ inputs.project-id }}
        INPUT_FILENAME: "result.json"
